# This script analyzes the damage foci data as generated by Geant4-DNA.

import numpy as np
import cv2
from scipy import ndimage

# region Importing data and intitalizing constants and lists

data = np.load('Geant4-DNA data .npy')

res = 0.05 # micron / px

fwhm = 0.261/(res)
sigma = fwhm/2.355

all_areas = []

# endregion

# region Blurring damage foci and calculating their areas

for i in range(len(data)):      # BECAUSE EVERY FOCI IS ISOLATED
    data_blurred = ndimage.gaussian_filter(data[i], sigma, 0)

    cv2.imshow('Alpha foci', data_blurred)
    cv2.waitKey(5000)

    non_zero = np.where(data_blurred>0)

    area = len(non_zero[1])*res*res

    all_areas.append(area)

np.savetxt('alpha_simulated_foci_areas.txt', all_areas)

# endregion
